### PR TITLE
Accommodate multiple css

### PR DESCRIPTION
**Pull request by avahoffman**
#### What changes are being implemented in this Pull Request?

Attempting a solution for https://github.com/jhudsl/OTTR_Template/issues/536. to accommodate:

```
bookdown::gitbook:
  css: [assets/style.css, assets/AnVIL_style/anvil.css]
```
#### What was your approach?

If multiple css files are provided in `_output.yml`, this now loops through and makes a "mega css" to proceed. 

Would appreciate if others can test/gut check this!

### CODE REVIEW

**Comment by cansavvy** [comment]
Thanks for doing this @avahoffman ! I'm gonna give this a deeper look tomorrow and get back to you.

**Comment by avahoffman** [comment]
Sounds great! I am hoping to be done with messing around with our AnVIL css :)

**Comment by cansavvy** [comment]
What repositories can I test this on? Does AnVIL_Template work as a good test?

**Comment by cansavvy** [comment]
Also, after this does run, what can I look at in your rendered AnVIL_Template to know that the multiple css files have all been incorporated? I'm not sure what I'm looking for. @avahoffman

**Review by cansavvy — APPROVED** [review]
This looks good to me. I ran it locally on AnVIL_Template and I'm pretty sure it worked but was wondering what a definitive item I should look for to know that it worked?

**Comment by avahoffman** [comment]
Good question haha. I tested it with toc-less.css and an 'anvil.css' both as args on `_output.yml`. 'anvil.css' had some css that changed the color and it appeared to work. I'll test further with a test docker image.

**Comment by cansavvy** [comment]
Sounds great. If that test docker image run works, then feel free to update the `:main` tagged docker image on `jhudsl/base_ottr`. Or I can also do that.

**Comment by avahoffman** [comment]
@cansavvy I will take care of it :)

**Pull request merged**
