### PR TITLE
handle duplicate file names

### PR DESCRIPTION
**Pull request by kweav**
This PR is for issue #136, attempting to handle if multiple chapters have the same name. 

The approach I took moved taking the screenshots outside of the lapply loop into a second one later. Instead the first lapply loop still returns the filenames (without the png extension) and passes that list to `make_clean_names()` from janitor which then should  add an underscore and number to distinguish duplicate filenames. After that, the list is passed to paste0 to add back the file extension. Finally, I moved storing the file names in the dataframe and then used a second lapply to take the screenshots.

### CODE REVIEW

**Review by cansavvy — COMMENTED** [review]
This seems reasonable to me! However, before we merge I just want to check how you tested this? 

Looks good though. Thanks for doing this!

**Comment by kweav** [comment]
I tested parts of the code locally, making a test vector with duplicated chapter names to see how the new code would behave. What steps/which repo do you recommend I should try for testing it?

**Comment by cansavvy** [comment]
> I tested parts of the code locally, making a test vector with duplicated chapter names to see how the new code would behave. What steps/which repo do you recommend I should try for testing it?

This seems reasonable to me! So I'm going to merge it!

**Review by cansavvy — APPROVED** [review]
Great work!

**Pull request merged**
